// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solve_ordered_binary_tree
NumericVector solve_ordered_binary_tree(NumericVector y_input, NumericVector w_input);
RcppExport SEXP _IsotoneOptimization_solve_ordered_binary_tree(SEXP y_inputSEXP, SEXP w_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_input(y_inputSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_input(w_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_ordered_binary_tree(y_input, w_input));
    return rcpp_result_gen;
END_RCPP
}
// solve_ordered_2d_grid
NumericVector solve_ordered_2d_grid(NumericVector y_input, NumericVector w_input);
RcppExport SEXP _IsotoneOptimization_solve_ordered_2d_grid(SEXP y_inputSEXP, SEXP w_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_input(y_inputSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_input(w_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_ordered_2d_grid(y_input, w_input));
    return rcpp_result_gen;
END_RCPP
}
// solve_ordered_arbitrary_DAG
NumericVector solve_ordered_arbitrary_DAG(NumericVector y_input, NumericVector w_input, NumericMatrix E_mat_input);
RcppExport SEXP _IsotoneOptimization_solve_ordered_arbitrary_DAG(SEXP y_inputSEXP, SEXP w_inputSEXP, SEXP E_mat_inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_input(y_inputSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w_input(w_inputSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type E_mat_input(E_mat_inputSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_ordered_arbitrary_DAG(y_input, w_input, E_mat_input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IsotoneOptimization_solve_ordered_binary_tree", (DL_FUNC) &_IsotoneOptimization_solve_ordered_binary_tree, 2},
    {"_IsotoneOptimization_solve_ordered_2d_grid", (DL_FUNC) &_IsotoneOptimization_solve_ordered_2d_grid, 2},
    {"_IsotoneOptimization_solve_ordered_arbitrary_DAG", (DL_FUNC) &_IsotoneOptimization_solve_ordered_arbitrary_DAG, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_IsotoneOptimization(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
