# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_ordered_chain <- function(y_input, w_input) {
    .Call('_IsotoneOptimization_solve_ordered_chain', PACKAGE = 'IsotoneOptimization', y_input, w_input)
}

solve_ordered_binary_tree <- function(y_input, w_input) {
    .Call('_IsotoneOptimization_solve_ordered_binary_tree', PACKAGE = 'IsotoneOptimization', y_input, w_input)
}

solve_ordered_2d_grid <- function(y_input, w_input) {
    .Call('_IsotoneOptimization_solve_ordered_2d_grid', PACKAGE = 'IsotoneOptimization', y_input, w_input)
}

solve_ordered_arbitrary_DAG <- function(y_input, w_input, E_mat_input) {
    .Call('_IsotoneOptimization_solve_ordered_arbitrary_DAG', PACKAGE = 'IsotoneOptimization', y_input, w_input, E_mat_input)
}

